version: v1.0
apiVersion: v1alpha
kind: Project
metadata:
  name: csid-event-lineage
  description: 'This repository holds OpenTelemetry Instrumentation extensions for Kafka Clients and Kafka Streams. Purpose of the extensions is to capture key/value payloads as they are Consumed and Produced by application.'
spec:
  visibility: private
  repository:
    url: 'git@github.com:confluentinc/csid-event-lineage.git'
    run_on:
      - branches
      - tags
      - pull_requests
    pipeline_file: .semaphore/semaphore.yml
    integration_type: github_app
    status:
      pipeline_files:
        - path: .semaphore/semaphore.yml
          level: pipeline
    whitelist:
      branches:
        - master
        - main
        - /^v\d+\.\d+\.x$/
  custom_permissions: true
  debug_permissions:
    - empty
    - default_branch
    - non_default_branch
    - pull_request
    - forked_pull_request
    - tag
  attach_permissions:
    - default_branch
    - non_default_branch
    - pull_request
    - forked_pull_request
    - tag